MVC-Example1/MVC-Example1/Models/ErrorViewModel.cs
namespace MVC_Example1.Models {
    public class ErrorViewModel {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC-Example1/MVC-Example1/Models/Persona.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MVC_Example1.Models {
    public class Persona {
        public string nome { get; set; }
        public string cognome { get; set; }
        public string telefono { get; set; }

        
        public Persona() { }
        public Persona(string nome, string cognome, string telefono) {
            this.nome = nome;
            this.cognome = cognome;
            this.telefono = telefono;
        }

        public override string ToString() {
            return "Nome: " + nome + "\nCognome: " + cognome + "\nTelefono: " + telefono;
        }
    }

}

MVC-Example1/MVC-Example1/Models/Rubrica.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace MVC_Example1.Models {
    public class Rubrica {
        private List<Persona> memoria;
        public string nome { get; }
        public Rubrica(string nome) {
            this.nome = nome;
            memoria = new List<Persona>();
        }

        public List<Persona> getMemoria() { return memoria; }

        private bool PersonaExist(Persona persona) {
            if (memoria.Any(personaMem => personaMem.telefono == persona.telefono)) {
                return true;
            } else {
                return false;
            }
        }

        public void AddPersona(Persona p) {
            if (PersonaExist(p)) {
                throw new Exception("Persona già in memoria");
            }
            memoria.Add(p);
        }

        public void UpdatePersona(String telefono, Persona p) {
            DeletePersona(telefono);
            AddPersona(p);
        }
        public Persona FindPersona(string telefono) {
            foreach (Persona persona in memoria) {
                if (persona.telefono == telefono) {
                    return persona;
                }
            }
            return null;
        }

        public void DeletePersona(string telefono) {
            Persona persona = FindPersona(telefono);
            if (persona != null) {
                memoria.Remove(persona);
            } else {
                throw new Exception("Persona non in memoria");
            }
        }

        public string getPrintableString() {
            string result = "";
            foreach (Persona persona in memoria) {
                result += persona.ToString();
            }
            return result;
        }
    }
}

MVC-Example1/MVC-Example1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Example1.Models;
using System.Diagnostics;

namespace MVC_Example1.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index() {
            return View();
        }

        public IActionResult Privacy() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC-Example1/MVC-Example1/Controllers/RubricaController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Example1.Models;

namespace MVC_Example1.Controllers {
    public class RubricaController : Controller {
        private static Rubrica rubrica = new Rubrica("Rubrica Personale");
        // Metodo Index per visualizzare la lista di contatti
        public IActionResult Index() {
            return View(rubrica);
        }


        // Metodo per mostrare il form di aggiunta contatto
        public IActionResult FormContatto() {
            return View();
        }

        // Metodo per aggiungere un nuovo contatto
        [HttpPost]
        public IActionResult AddPersona(Persona persona) {
            try {
                rubrica.AddPersona(persona);
                return RedirectToAction("Index");
            } catch (Exception ex) {
                // Gestione errore (persona già presente)
                ViewBag.ErrorMessage = ex.Message;
                return View("FormContatto");
            }
        }

        // Metodo per modificare un nuovo contatto
        [HttpPost]
        public IActionResult UpdatePersona(String telefono,Persona p) {
            try {
                rubrica.UpdatePersona(telefono, p);
                return RedirectToAction("Index");
            } catch (Exception ex) {
                // Gestione errore (persona già presente)
                ViewBag.ErrorMessage = ex.Message;
                return View("FormContatto");
            }
        }


        // Metodo per cancellare un contatto (passa il telefono come identificatore)

        public IActionResult DeletePersona(string telefono) {
            try {
                rubrica.DeletePersona(telefono);
            } catch (Exception ex) {
                // Messaggio di errore se la persona non esiste
                ViewBag.ErrorMessage = ex.Message;
            }
            return RedirectToAction("Index");
        }
    }
}

MVC-Example1/MVC-Example1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Rubrica Telefonica MVC</h1>
</div>

MVC-Example1/MVC-Example1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rubrica Telefonica MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_Example1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rubrica Telefonica MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="/" asp-action="Index">Rubrica Telefonica</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Rubrica Telefonica MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC-Example1/MVC-Example1/Views/rubrica/Index.cshtml
@model MVC_Example1.Models.Rubrica

<h1>@Model.nome</h1>

<a href="@Url.Action("FormContatto", "Rubrica")">Aggiungi nuovo contatto</a>

<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>

<table>
    <tr>
        <th>Nome</th>
        <th>Cognome</th>
        <th>Telefono</th>
        <th>Elimina Contatto</th>

    </tr>

    @foreach (var persona in Model.getMemoria()) {
        <tr>
            <td>@persona.nome</td>
            <td>@persona.cognome</td>
            <td>@persona.telefono</td>
            <td>
                <a href="@Url.Action("DeletePersona", "Rubrica", new { telefono = persona.telefono })">Elimina</a>
            </td>
        </tr>
    }

</table>

MVC-Example1/MVC-Example1/Views/rubrica/formContatto.cshtml
@model MVC_Example1.Models.Persona

<h2>Aggiungi un nuovo contatto</h2>

@if (ViewBag.ErrorMessage != null) {
    <p style="color: red;">@ViewBag.ErrorMessage</p>
}

<form asp-action="AddPersona" asp-controller="Rubrica" method="post">
    <table>
        <tr>
            <td>
                <label>Nome:</label>
            </td>
            <td>
                <input type="text" name="nome" required /><br />
            </td>
        </tr>
        <tr>
            <td>
                <label>Cognome:</label>
            </td>
            <td>
                <input type="text" name="cognome" required /><br />
            </td>
        </tr>
        <tr>
            <td>
                <label>Telefono:</label>
            </td>
            <td>
                <input type="text" name="telefono" required /><br />
            </td>
        </tr>
        <tr>
            <td>
                <button type="submit">Aggiungi</button>
            </td>
        </tr>
    </table>
</form>