MVC-ComuniItaliani/MVC-ComuniItaliani/Models/ErrorViewModel.cs
namespace MVC_ComuniItaliani.Models {
	public class ErrorViewModel {
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

MVC-ComuniItaliani/MVC-ComuniItaliani/ViewModels/ComuniISTATElencoComuniViewModel.cs
using FunzioniISTAT.Modelli;
namespace MVC_ComuniItaliani.ViewModels {
    public class ComuniISTATElencoComuniViewModel {
        public Comune[] ElencoComuni { get; set; }
    }
}

MVC-ComuniItaliani/MVC-ComuniItaliani/Controllers/ComuniController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_ComuniItaliani.ViewModels;
using FunzioniISTAT;
using FunzioniISTAT.Modelli;


namespace MVC_ComuniItaliani.Controllers {
    public class ComuniController : Controller {
        public IActionResult Index() {
            ComuniISTATElencoComuniViewModel vm = new ComuniISTATElencoComuniViewModel();

            Comune[] elencoComuni = FunzioniInterrogazioneISTAT.getElencoComuni();
            vm.ElencoComuni = elencoComuni;
            return View(vm);
        }


    }
}

MVC-ComuniItaliani/MVC-ComuniItaliani/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_ComuniItaliani.Models;
using System.Diagnostics;

namespace MVC_ComuniItaliani.Controllers {
	public class HomeController : Controller {
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger) {
			_logger = logger;
		}

		public IActionResult Index() {
			return View();
		}

		public IActionResult Privacy() {
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error() {
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

MVC-ComuniItaliani/MVC-ComuniItaliani/Views/Comuni/Index.cshtml
@using MVC_ComuniItaliani.ViewModels
@model ComuniISTATElencoComuniViewModel


<!DOCTYPE html>
<html>
<head>
    <title>Comuni Italiani</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Elenco dei Comuni Italiani</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Codice Catastale</th>
                    <th>Denominazione in Italiano</th>
                    <th>Ripartizione Geografica</th>
                    <th>Denominazione Regione</th>
                    <th>Denominazione Unità Sovracomunale</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var comune in Model.ElencoComuni) {
                        <tr>
                            <td>@comune.CodiceCatastaleComune</td>
                            <td>@comune.DenominazioneItaliano</td>
                            <td>@comune.RipartizioneGeografica</td>
                            <td>@comune.DenominazioneRegione</td>
                            <td>@comune.DenominazioneUnitaSovracomunale</td>
                        </tr>
                    }
            </tbody>
        </table>
    </div>
</body>
</html>

MVC-ComuniItaliani/MVC-ComuniItaliani/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Servizio Visualizzazione Comuni Italiani</h1>
</div>

MVC-ComuniItaliani/MVC-ComuniItaliani/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_ComuniItaliani</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_ComuniItaliani.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_ComuniItaliani</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Comuni" asp-action="">COMUNI</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVC_ComuniItaliani - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>